apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxmed-bot-svc
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: luxmed-bot-svc
  template:
    metadata:
      labels:
        app: luxmed-bot-svc
    spec:
      containers:
      - image: python-imagename
        name: luxmed-bot-svc
        ports:
        - containerPort: 8443