apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxmed-bot-svc
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: luxmed-bot-svc
  template:
    metadata:
      labels:
        app: luxmed-bot-svc
    spec:
      containers:
      - image: luxmed:local
        name: luxmed-bot-svc
        imagePullPolicy: Never
        env:
        - name: TG_TOKEN
          valueFrom:
            secretKeyRef:
              name: tg-token
              key: tg-token
        - name: PROXY_USER
          valueFrom:
            secretKeyRef:
              name: proxy-user
              key: proxy-user
        - name: PROXY_PASS
          valueFrom:
            secretKeyRef:
              name: proxy-pass
              key: proxy-pass
        - name: DZIANIS_USER
          valueFrom:
            secretKeyRef:
              name: dzianis-user
              key: dzianis-user
        - name: DZIANIS_PASS
          valueFrom:
            secretKeyRef:
              name: dzianis-pass
              key: dzianis-pass
        ports:
        - containerPort: 8443